# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    # implicit-dynamic: false

linter:
  rules:
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - annotate_overrides
    - hash_and_equals
    - prefer_is_not_empty
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - avoid_init_to_null
    # - constant_identifier_names
    - one_member_abstracts
    - slash_for_doc_comments
    - sort_constructors_first
    - unnecessary_brace_in_string_interps

    # === doc rules ===
    # - public_member_api_docs

    # ignore specify types
    # - always_specify_types
    # ignore const for now
    # - prefer_const_constructors
