name: build

on: [push, pull_request]

jobs:
  build_android_debug:
    name: Build Android Debug on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed .
      - run: flutter pub publish --dry-run
      - run: flutter analyze lib example/lib
      - run: cd example; flutter build apk --debug

  build_android_release:
    name: Build Android Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed .
      - run: flutter pub publish --dry-run
      - run: flutter analyze lib example/lib
      - run: cd example; flutter build apk
      - run: ls example/build/app/outputs/apk/walle/channels/
      - run: ls example/build/app/outputs/apk/walle/channels/market/
